[internal] Fix pre-commit hook to work on Apple Silicon
# Rust tests and lints will be skipped. Delete if not intended.
[ci skip-rust]

# Building wheels and fs_util will be skipped. Delete if not intended.
[ci skip-build-wheels]

diff --git a/build-support/githooks/pre-commit b/build-support/githooks/pre-commit
--- a/build-support/githooks/pre-commit
+++ b/build-support/githooks/pre-commit
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 
-# NB: pre-commit runs in the context of GIT_WORK_TREE, ie: pwd == REPO_ROOT
+set -e
 
+# NB: pre-commit runs in the context of GIT_WORK_TREE, ie: pwd == REPO_ROOT
 source build-support/common.sh
 
 # Commit hooks set $GIT_DIR by default to .git
@@ -13,48 +14,27 @@ if [[ -n "${GIT_DIR}" && "${GIT_DIR}" != /* ]]; then
   export GIT_DIR
 fi
 
-set -e
-
 MERGE_BASE="$(git_merge_base)"
 
-# When travis builds a tag, it does so in a shallow clone without main fetched, which
-# fails in pants changed.
-if git rev-parse --verify "${MERGE_BASE}" &> /dev/null; then
-  if git diff "${MERGE_BASE}" --name-only | grep '\.rs$' > /dev/null; then
-    # Clippy happens on a different Travis CI shard because of separate caching concerns.
-    # The TRAVIS env var is documented here:
-    #   https://docs.travis-ci.com/user/environment-variables/#default-environment-variables
-    if [[ "${TRAVIS}" != "true" ]]; then
-      echo "* Running \`./cargo clippy --all\`"
-      ./cargo clippy --all || exit 1
-    fi
-    echo "* Checking formatting of Rust files"
-    ./build-support/bin/check_rust_formatting.sh || exit 1
-    echo "* Checking Rust target headers"
-    build-support/bin/check_rust_target_headers.sh || exit 1
-  fi
+if git diff "${MERGE_BASE}" --name-only | grep '\.rs$' > /dev/null; then
+  echo "* Running \`./cargo clippy\`"
+  ./cargo clippy || exit 1
+  echo "* Checking formatting of Rust files"
+  ./build-support/bin/check_rust_formatting.sh || exit 1
+  echo "* Checking Rust target headers"
+  build-support/bin/check_rust_target_headers.sh || exit 1
+fi
 
-  echo "* Checking MyPy"
-  ./pants --changed-since="${MERGE_BASE}" --changed-dependees=transitive --tag='-nolint' typecheck || exit 1
+echo "* Checking linters and formatters"
+./pants --changed-since="${MERGE_BASE}" --tag='-nolint' lint ||
+  die "If there were formatting errors, run \`./pants --changed-since=$(git rev-parse --symbolic "${MERGE_BASE}") fmt\`"
 
-  echo "* Checking linters and formatters"
-  ./pants --changed-since="${MERGE_BASE}" --tag='-nolint' lint ||
-    die "If there were formatting errors, run \`./pants --changed-since=$(git rev-parse --symbolic "${MERGE_BASE}") fmt\`"
+echo "* Checking MyPy"
+./pants --changed-since="${MERGE_BASE}" --changed-dependees=transitive --tag='-nolint' typecheck || exit 1
 
-  if git diff "${MERGE_BASE}" --name-only | grep build-support/bin/generate_travis_yml.py > /dev/null; then
-    echo "* Checking .travis.yml generation"
-    actual_travis_yml=$(< .travis.yml)
-    expected_travis_yml=$(./pants run build-support/bin:generate_travis_yml)
-    [ "${expected_travis_yml}" == "${actual_travis_yml}" ] ||
-      die "Travis config generator changed, but .travis.yml file was not regenerated. See the header of .travis.yml for instructions."
-  fi
-
-  if git diff "${MERGE_BASE}" --name-only | grep build-support/bin/generate_github_workflows.py > /dev/null; then
-    echo "* Checking GitHub workflows generation"
-    ./pants run build-support/bin/generate_github_workflows.py -- --check
-  fi
-else
-  echo "* Skipping import/lint checks in partial working copy."
+if git diff "${MERGE_BASE}" --name-only | grep build-support/bin/generate_github_workflows.py > /dev/null; then
+  echo "* Checking GitHub workflows generation"
+  ./pants run build-support/bin/generate_github_workflows.py -- --check || exit 1
 fi
 
 echo "* Checking shell scripts via our custom linter"
